spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  sql:
    init:
      mode:
      platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://surus.db.elephantsql.com:5432/emmdgbuc
    username: emmdgbuc
    password: pDay9rjrykggzx0nRBgBVwIo4Bu-Ilrx
    tomcat:
      max-wait: 10000
      max-active: 1
      test-on-borrow: true
      max-idle: 1